#!/usr/bin/env bash

for f in src/*.typ; do
    if [ $f = src/index.typ ]; then
        set outdir .
    else
        outdir=$(basename -s .typ $f)
        if [ ! -d $outdir ]; then
            mkdir $outdir
        fi
    fi
    echo compiling $f to $outdir/index.html
    typst compile $f --features html --format html --root . $outdir/index.html
done
